version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Cached build dependencies
      - restore_cache:
          keys:
            - dependencies-build-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - dependencies-build-{{ .Branch }}
            - dependencies-build

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: dependencies-build-{{ .Branch }}-{{ checksum "requirements.txt" }}

  unit_tests:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Cached test dependencies
      - restore_cache:
          keys:
            - dependencies-ci-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}
            - dependencies-ci-{{ .Branch }}
            - dependencies-ci
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r .circleci/requirements.txt
      - save_cache:
          when: always
          paths:
            - "venv"
          key: dependencies-ci-{{ .Branch }}-{{ checksum ".circleci/requirements.txt" }}

      - run:
          name: unit_tests
          command: |
            . venv/bin/activate
            pip install -e .
            coverage run -m unittest discover test/
            coverage xml

      - codecov/upload:
          file: coverage.xml
          flags: unittest
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - unit_tests